spring:
  datasource:
    username: root
    password: Daohaosima1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/choose_class

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*.xml

server:
  port: 9090

logging:
  file:
    name: log/log.log
  level:
    root: info
    com.dbcourse.classchoose: debug